spring:
  jmx:
    enabled: false

server:
  port: 8090

logging:
  file:
    path: ./
    name: usoamicexplorer.log
  org.hibernate: INFO

usoamic:
  ticker: 'USO'
  account-file-name: 'account.json'
  wallet-password: '1234'
  date-format: 'yyyy-MM-dd HH:mm'
  node-provider: 'INFURA'
  network-type: 'MAINNET' #'TESTNET'
  project-id: 'fa8e5195184149f79e644292d2b31707'