spring:
  jmx:
    enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/usoamicapp-db
    driverClassName: org.postgresql.Driver
    username: usoamicapp-user
    password: usoamicapp-password

  flyway:
    enabled: true
    baselineOnMigrate: true
    schemas: usoamicapp

  jpa:
    hibernate.ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8090

logging:
  file:
    path: ./
    name: usoamicapp.log
  org.hibernate: INFO

usoamic:
  ticker: 'USO'
  account-file-name: 'account.json'
  wallet-password: '1234'
  date-format: 'yyyy-MM-dd HH:mm'
  node-provider: 'infura'
  network-type: 'MAINNET' #'TESTNET'
  project-id: 'fa8e5195184149f79e644292d2b31707'